### ISSUE TITLE
Generate shopping cart and purchase order

### ISSUE THREAD

**Issue by hugocruz1234** [BrightCoders-Institute/proyecto-final-jdg#28]
## REQUIREMENTS / DESCRIPTION

Implement a shopping cart, where the user can do the following:
- Add/Remove products.
- View products in the cart

Then, based on the above, be able to generate a purchase order, which will show the following:
- Items purchased.
- Quantity and price of the product.
- Unit price.
- Total of the transaction.
- Customer name.
- Customer's address.

**Comment by Ballo1988** [comment]
Already done
