### ISSUE TITLE
Create Styles for Shopping Cart and Order Views

### ISSUE THREAD

**Issue by sr-meh** [BrightCoders-Institute/proyecto-final-jdg#37]
### Description:

Currently, the shopping cart and order views lack cohesive and attractive visual styles. This can negatively affect the user experience when interacting with these essential sections of the application. Proper styling and creation are required to improve the appearance and usability of these views, providing a visually consistent and pleasing experience for users.

### Tasks to be done:

- Design a color palette that is consistent with the visual identity of the brand and that adapts to the existing interface.
- Create CSS styles for cart and order views, including elements such as buttons, tables, headers, and footers.
- Implement responsive layouts to ensure views look and work correctly on different screen sizes.
- Use legible and appropriate fonts to improve the readability of the content in the views.
- Add subtle visual effects and transitions to improve interaction and a sense of fluidity when navigating views.
- Make sure that the styles created do not negatively affect the performance of the application.

### Criteria of acceptance:

- The shopping cart and order views have a consistent and attractive visual appearance.
- The colors, fonts, and visual elements used are consistent with the brand identity.
- The designs are responsive and look good on different devices and screen sizes.
- The readability of the content is improved by the use of suitable typefaces and appropriate text sizes.

**Comment by Ballo1988** [comment]
Done
