### ISSUE TITLE
Apply Styles and Access Restrictions to the Product Details View for Users

### ISSUE THREAD

**Issue by sr-meh** [BrightCoders-Institute/proyecto-final-jdg#38]
### Description:

The current product details view is used both for administrators to view and edit product details and for users to view the details of a product. However, it is necessary to apply a visual and functional differentiation in the view according to the type of user. Admins should be able to access editing and deleting features, while regular users should have a different view without access to those features and with styles that align with the brand's visual identity.

### Tasks to be done:

- Identify and set access restrictions based on the type of user (administrator or regular user) to show or hide the edit and delete buttons.
- Design a visually distinct interface for the product details view that is presented to regular users.
- Apply CSS styles that are consistent with the brand identity and that provide an engaging visual experience for users.
- Develop logic that shows or hides elements according to the type of authenticated user.
- Ensure that the changes do not negatively affect the performance of the application and that they remain responsive.

### Criteria of acceptance:

- The product details view is presented differently depending on the type of user (administrator or regular user).
- The edit and delete buttons are only available to administrators and are hidden from regular users.
- The styles applied to the product details view are consistent with the visual identity of the brand.
- Changes to the view do not affect the overall functionality of the app and it stays responsive across different devices.
- A thorough review is done to make sure that the constraint logic and styles are applied correctly.

**Comment by Ballo1988** [comment]
Done
