### ISSUE TITLE
Fix Navigation Bar Elements and Styles to Improve User Experience

### ISSUE THREAD

**Issue by sr-meh** [BrightCoders-Institute/proyecto-final-jdg#39]
### Description:
The current navigation bar has problems in terms of its design and display on different devices. In mobile view, the layout is not displayed correctly, affecting the user experience by making navigation difficult. Also, in the desktop view, the login button is not displayed properly, which can lead to confusion for users. Fixing these issues by adjusting the styles and elements of the navigation bar is required to ensure a consistent and functional experience across all devices.

### Tasks to be done:

- Identify the specific problems in the design of the navigation bar in the mobile view and in the desktop view.
- Adjust the CSS styles of the navigation bar so that it displays correctly on mobile devices, ensuring that the elements are readable and clickable.
- Resolve the issue with the login button in desktop view so it displays properly and is easily recognizable.
- Perform extensive testing on different screen sizes to verify that the changes work consistently.

### Criteria of acceptance:

- The navigation bar is displayed properly and readably in the mobile view, with clickable and consistently designed elements.
- The desktop view login button displays correctly and is easily identifiable.
- Changes made to styles do not negatively affect navigation bar performance or cause visual issues on other screen sizes.
- Testing on different devices and confirming that the navigation bar works correctly in all views.

**Comment by Ballo1988** [comment]
Done
